/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutValidationImport } from './routes/_layout/validation'
import { Route as LayoutSmartRepositoryImport } from './routes/_layout/smart-repository'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutLspManagementImport } from './routes/_layout/lsp-management'
import { Route as LayoutGenerationImport } from './routes/_layout/generation'
import { Route as LayoutExtractionImport } from './routes/_layout/extraction'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutValidationRoute = LayoutValidationImport.update({
  path: '/validation',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSmartRepositoryRoute = LayoutSmartRepositoryImport.update({
  path: '/smart-repository',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLspManagementRoute = LayoutLspManagementImport.update({
  path: '/lsp-management',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGenerationRoute = LayoutGenerationImport.update({
  path: '/generation',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExtractionRoute = LayoutExtractionImport.update({
  path: '/extraction',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/extraction': {
      preLoaderRoute: typeof LayoutExtractionImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/generation': {
      preLoaderRoute: typeof LayoutGenerationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/lsp-management': {
      preLoaderRoute: typeof LayoutLspManagementImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/smart-repository': {
      preLoaderRoute: typeof LayoutSmartRepositoryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/validation': {
      preLoaderRoute: typeof LayoutValidationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutExtractionRoute,
    LayoutGenerationRoute,
    LayoutLspManagementRoute,
    LayoutSettingsRoute,
    LayoutSmartRepositoryRoute,
    LayoutValidationRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
])

/* prettier-ignore-end */
