version: '3.9'

services:
  db:
    container_name: spalsp-db
    build: ./src/shared/db
    volumes:
      - /docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
